import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";


const cairoFont = Cairo({
  variable: "--font-cairo",
  subsets: ["latin", "arabic"], 
  weight: ["400", "700"], 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cairoFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
