import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import Head from "next/head";


const cairoFont = Cairo({
  variable: "--font-cairo",
  subsets: ["latin", "arabic"], 
  weight: ["400", "700"], 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<html lang="en">
  <Head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  </Head>
  <body className={`${cairoFont.variable} antialiased`}>
    {children}
  </body>
</html>

  );
}
